### ISSUE TITLE
로그인 후 재로그인 시 415 에러 발생

### ISSUE THREAD

**Issue by dailyworker** [programmer-ground/ProgrammerGround#118]
```
org.springframework.web.client.HttpClientErrorException$UnsupportedMediaType: 415 Unsupported Media Type: [{"message":"If you would like to help us test the Commit Search API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details.","documentation_url":"https://docs.github.com/rest/reference/search#search-commits"}]
```
[참고 api 문서](https://docs.github.com/rest/reference/search#search-commits)

**Comment by dailyworker** [comment]
![Screen Shot 2021-08-16 at 21 45 31](https://user-images.githubusercontent.com/22961251/129565975-0b803167-ef72-4bf6-929e-7d471105fd98.png)

[Media-type](https://docs.github.com/en/rest/overview/media-types)
[API Preview](https://docs.github.com/en/rest/overview/api-previews)

commit 개수를 가져오는 부분은 API Preview로 아직 오피셜에 반영되지 않은 사항임.
따라서, `Accept Header` 를 Preview 형식에 맞는 놈으로 설정해서 해야한다.

**Comment by thdwlsgus0** [comment]
잘됩니당 ㅎㅎ
