### ISSUE TITLE
알림 신청 api 파라미터 질문

### ISSUE THREAD

**Issue by thdwlsgus0** [programmer-ground/ProgrammerGround#133]
- 이 부분에서  혹시 position_id는 어느 파라미터를 가져와야 하나여? playground리스트에서 가져오면 되는줄 알았는데 playground에는 없는 것 같아서 만약 없으면 playground/{playgroundId} get 요청 api에 저 파라미터 추가좀.. 있으면 위치좀 알려주시면 감사하겠습니다!!

<img width="1414" alt="스크린샷 2021-09-11 오전 4 47 23" src="https://user-images.githubusercontent.com/22065725/132909610-3225f926-e266-4ffd-af80-e5f3603c1526.png">

**Comment by dailyworker** [comment]
현재 우리는 아래와 같은 이늄으로 position의 id를 받아오고 있음. 

```.java
public enum Position {
    BACKEND, FRONTEND, DESIGN, PLANNER, DEVOPS
}
```

그러나, 이 리스트를 가져오는 api는 따로 없으므로 이 api가 필요할 것으로 생각이 됌.

따라서서, 아래의 흐름으로 처리되기 위해서 position enum의 값을 리스트로 전달하는 api가 필요한 상황 

<img width="1235" alt="Screen Shot 2021-09-11 at 10 54 31" src="https://user-images.githubusercontent.com/22961251/132932521-f33522b8-5a26-47a7-99e2-75fb75c5c225.png">

**Comment by dailyworker** [comment]
현재 필요한 부분은 `PlaygroundPosition` 의 id 값이므로 위의 부분을 추가하면서 추가 구현 예정
