### ISSUE TITLE
api 파라미터 추가 요청 

### ISSUE THREAD

**Issue by thdwlsgus0** [programmer-ground/ProgrammerGround#136]
- 현재 leader notice get api를 연동한 상황인데 날짜 관련 속성이 api에 있으면 좋을 것 같아서 요청드립니다!!
<img width="358" alt="스크린샷 2021-09-22 오후 5 16 48" src="https://user-images.githubusercontent.com/22065725/134307818-d5c80e23-6e9a-4465-b9dd-c4dead09706d.png">

- 요청사항
   - /user/notices/leader 요청 시간 속성 추가
   - /user/notices/results 요청 시간 속성 추가
   - /user/notices/waitings 요청 시간 속성 추가

**Comment by dailyworker** [comment]
@CJW23 개발완료되었나요? 아직 안되었으면 제가 하겠습니다.
