### ISSUE TITLE
repository 생성 api client 500 error + server 401 error  

### ISSUE THREAD

**Issue by thdwlsgus0** [programmer-ground/ProgrammerGround#146]
- repository 생성 api를 연결하는 과정에서 다음의 에러가 발생합니다.
<img width="799" alt="스크린샷 2021-10-04 오후 2 46 02" src="https://user-images.githubusercontent.com/22065725/135800124-dac35810-8ec0-4b9a-8ed0-7bd56d283d09.png">

- 찾아보니 다음과 같은 이슈인 것 같아여..
- https://www.wrapuppro.com/programing/view/RATfDYjVrxvnkK8

**Comment by dailyworker** [comment]
이 부분은 저번에 말씀드린 것과 같이 github-bot AccessToken이 만료되서 생긴 문제였고, 올려드린 토큰으로 확인하시면 될거같습니다.

**Comment by thdwlsgus0** [comment]
금주내로 확인 예정
