### ISSUE TITLE
로그인 버튼 누를 시 이상한 url로 요청됨

### ISSUE THREAD

**Issue by thdwlsgus0** [programmer-ground/ProgrammerGround#180]
- 이슈 : 로그인 버튼을 누른 뒤 이슈 발생
- 작업했던 것 
   - auth, pg => profiles.active=dev, environment variables 설정
   - 서버 정상 실행 및 동작
- 현상 
   - http://localhost:8080/oauth2/authorization/github의 주소로 a링크를 이용해서 보내주면 이상한 url로 이동하게 됨
   <img width="1592" alt="스크린샷 2021-12-26 오전 12 42 17" src="https://user-images.githubusercontent.com/22065725/147388561-d9e0181b-112e-422d-baff-6fb197ff7eb2.png">
   <img width="950" alt="스크린샷 2021-12-26 오전 12 43 16" src="https://user-images.githubusercontent.com/22065725/147388579-375fcce4-724c-440d-9541-b1056b0304ec.png">
   <img width="709" alt="스크린샷 2021-12-26 오전 12 50 01" src="https://user-images.githubusercontent.com/22065725/147388704-3d2b5ba2-6aab-4219-ad20-acf542a24e78.png">
   
<img width="1062" alt="스크린샷 2021-12-26 오전 12 51 21" src="https://user-images.githubusercontent.com/22065725/147388724-93259e19-7aaf-4bdb-8b8e-aa1e081b54f8.png">

 - 전달되는 url : https://github.com/login/oauth/authorize?response_type=code&client_id=test&scope=public_repo%20read:user&state=m6VnU7wZ7PJOWku_0wHIdSVsCyDYpQcKOMd_t2-jSjE%3D&redirect_uri=http://localhost:8080/login/oauth2/code/github
 - 혹시 url이나 제가 따로 추가적으로 세팅해야될 부분이 있을까요

**Comment by brewagebear** [comment]
샘플 환경변수로 설정하여 발생한 이슈같아 보입니다. 이슈 클로즈할테니 수정 후 문제 생기면 리오픈해주세요.
