### ISSUE TITLE
PG api 500 에러 이슈 

### ISSUE THREAD

**Issue by thdwlsgus0** [programmer-ground/ProgrammerGround#183]
- 이슈: PG api 500 에러 이슈가 발생하는 것 같아요~
- 체크리스트
   - 프론트인지 백인지 확인해봐야 알겠지만 500에러가 떠서 일단 이슈로 등록하겠습니다.
   - invalid token이라는 게 뜨는 걸보면 이거랑 관련되지 않았을까 생각합니다.
  
   - auth 로그
   
<img width="1305" alt="스크린샷 2021-12-28 오후 5 27 54" src="https://user-images.githubusercontent.com/22065725/147545703-aa6e4d17-528f-4230-9d1d-bb5831366d6e.png">

   - pg 로그
<img width="1300" alt="스크린샷 2021-12-28 오후 5 28 18" src="https://user-images.githubusercontent.com/22065725/147545731-e0b09bf5-3b46-4178-8c7c-0139d8f2a437.png">

   - 클라이언트 에러 
  <img width="518" alt="스크린샷 2021-12-28 오후 5 28 54" src="https://user-images.githubusercontent.com/22065725/147545784-304f96fd-8f2c-428d-aae3-33760008ff21.png">
  <img width="496" alt="스크린샷 2021-12-28 오후 5 29 22" src="https://user-images.githubusercontent.com/22065725/147545840-9210b22c-33e5-4c82-ba14-957e29cf845c.png">
   
   - postman test 
<img width="883" alt="스크린샷 2021-12-28 오후 5 30 39" src="https://user-images.githubusercontent.com/22065725/147545963-2c864696-fc98-4ea8-9ae4-74bd602d34e6.png">

**Comment by brewagebear** [comment]
어떤 엔드포인트 호출되었을 경우 재현이 되는지 상세 시나리오 작성해주시면 더 도움이 되실거같습니다.

**Comment by thdwlsgus0** [comment]
- 로그인 -> 나의 프로필 500 error (http://localhost:3000/profile)
      - api: (http://localhost:9000/user, http://localhost:9000/playground)
- 로그인 -> playground all 500 error(http://localhost:3000) 부분에서 에러가 나타나는 것 같습니다.
 
제 생각에는 pg에서 api 요청 과정에서 auth 인증이 잘 이루어지지 않는 것 같습니다.

**Comment by brewagebear** [comment]
에러 재현이 되서 남겨봅니다.

로그인 에러 : undefined로 리다이렉트가 됩니다.  
`java.lang.IllegalArgumentException: JWT String argument cannot be null or empty.`

로그인 Axios 쪽 한번 확인해봐야할 거 같습니다. 

`GET_JWT_TOKEN: ${process.env.REACT_APP_GET_OAUTH_TOKEN}` 이 값이 올바르게 넘어오는지 확인 필요합니다.

**Comment by brewagebear** [comment]
`env.developement` 추가하여 로그인 부분 문제 수정완료하였고, 현재 PG-API 쪽 로그가 제대로 안남는 상황이라 이 부분 상세 로그 남기고 테스트 수행해보겠습니다.

원인은 아마도 `/user` api 호출할 때 제대로 token이 안넘어가는거같습니다.

**Comment by thdwlsgus0** [comment]
형 혹시 프론트문제라고 생각이 들면 말씀해주세요!

**Comment by CJW23** [comment]
JWT application.yml api쪽에 선언 안해서 생긴 오류

**Comment by CJW23** [comment]
해결
