### ISSUE TITLE
Github API Serialize 문제

### ISSUE THREAD

**Issue by dailyworker** [programmer-ground/ProgrammerGround#80]
+ 아래와 같이 `ResponseEntity.class` 로 `RestTemplate` 기반 API call 처리할 때
![Screen Shot 2021-05-13 at 1 41 27 PM](https://user-images.githubusercontent.com/22961251/118078422-b30ecf00-b3a5-11eb-9a21-23f8ef5c5be6.png)

+ 다음과 같이 Serialize 문제가 발생 
![Screen Shot 2021-05-13 at 1 41 33 PM](https://user-images.githubusercontent.com/22961251/118078411-aee2b180-b3a5-11eb-9835-91d178ab6f54.png)

아마도 DTO 추가를 안하고 떙겨와서 그런거같은데 `modelMapper` 로 처리하여 수정할 예정

**Comment by LoveAndCode** [comment]
```java
@Service
@RequiredArgsConstructor
public class GithubRestService {
    private final HttpComponentsClientHttpRequestFactory factory;
    private final RestTemplate restTemplate;

    @Autowired
    public GithubRestService() {
        this.factory = new HttpComponentsClientHttpRequestFactory();
        this.factory.setReadTimeout(5000);
        this.factory.setConnectionRequestTimeout(5000);
        this.restTemplate = new RestTemplate(this.factory);
    }

    /**
     * Rest 통신
     */
    public <T> T rest(String url, HttpMethod method, HttpHeaders header, Class<T> response) {
        return restTemplate.exchange(url, method, new HttpEntity<>(header), response).getBody();
    }

}

```
getBody메서드가 호출되기 때문에, ResponseEntity로 받을 수 없을 것 같아요
